name = "Segment7"
artist = "Cedric Knight"
license = "OFL 1.1"
year = 2014
url = "https://www.fontspace.com/cedders/segment7"
comments = """
This file was modified from the original by converting from OTF to TTF using
https://convertio.co/otf-ttf/
"""
