name = "Sheet Of Aluminium Brushed Metal Texture"
artist = "www.myfreetextures.com"
license = "CC-BY"
year = 2014
url = "http://www.myfreetextures.com/sheet-of-aluminium-brushed-metal-texture/"
comments = """
This file was modified from the original by cropping it from 3500×3500 pixels
to a 64x64 subsection.
"""
