name = "Pitch Black"
artist = "Jens Kiilstofte"
license = "CC-BY 4.0"
year = 2014
url = "https://machinimasound.com/legacy-tracks"
comments = """
This file was modified from the original by (1) mixing stereo down to mono, (2)
shortening the fade out time at the end, and (3) converting from MP3 to Ogg
Vorbis.
"""
