name = "Seamless Space Tile"
artist = "Prawny"
license = "Free"
year = 2015
url = "http://www.prawny.me.uk/media.details.php?mediaID=NzU0NmM3ZDM1ZGJiZWI="
comments = """
Found at https://www.publicdomainpictures.net/en/view-image.php?image=126214
This file was modified from the original by resizing from 1920x1920 to
2048x2048.
"""
