name = "60 Terrible Character Portraits"
artist = "Jeff Preston"
license = "CC-BY 3.0"
year = 2011
url = "http://kck.st/dogX5W"
comments = """
Also at https://opengameart.org/content/60-terrible-character-portraits
These files were modified from the originals by cropping and scaling down.
"""
