name = "Red Desert"
artist = "Spiral Graphics"
license = "Royalty Free"
year = 2019
url = "http://spiralgraphics.biz/packs/terrain_desert_barren/index.htm?27"
comments = """
Full license terms at http://spiralgraphics.biz/packs/usage_rights.htm
"""
